name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run gluac
      run: |
        wget https://github.com/Metastruct/gtravis/releases/download/travisbins/gluac.tar.xz
        tar -xf gluac.tar.xz
        export LD_LIBRARY_PATH=`pwd`/gluac${LD_LIBRARY_PATH:+:}${LD_LIBRARY_PATH:-}
        export PATH=$PATH:`pwd`/gluac
        chmod u+x ./gluac
        find . -type f -name '*.lua' -not -path '*/gmod_wire_expression2/core/custom/*' -print0 | xargs -0 -- gluac -p --
